### ISSUE TITLE
Remove "\n" at the end of public_key_openssh in tls_private_key resource

### ISSUE THREAD

**Issue by ujjwal-ibm** [hashicorp/terraform-provider-tls#163]
### Terraform CLI and Provider Versions

Terraform v1.0.9

### Terraform Configuration

```terraform
resource "tls_private_key" "insecure" {
  algorithm = "RSA"
  rsa_bits  = 4096
}
```

### Expected Behavior

public_key_openssh attribute should be generated without new line character

### Actual Behavior

public_key_openssh attribute is generated with new line character

           ` "public_key_openssh": "ssh-rsa ......==\n",`

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by detro** [comment]
Hello @ujjwal-ibm, thanks for opening this issue.

So, I did a bit of research, and it turns out that it's an established convention to generate OpenSSH Public Key in a `~/.ssh/authorized_keys` friendly format. That means that each entry is ready to be appended to `authorized_keys` as is. And the newline works as a "termination" for the key.

I can't pin point to an RFC for this unfortunately, but suggest a bit of googling around.

Additional to this, I have looked at how exactly that newline get appended: turns out this is baked into [`MarshalAuthorizedKey(key PublicKey)`](https://github.com/golang/crypto/blob/master/ssh/keys.go#L288) in `x/crypto/ssh` itself. This is the official cryptography library for Golang, so I tend to rely on the fact that who wrote this knows more than I do on what's right for those formats and conventions.

Lastly, even if we wanted to make a change like this, it would most definitely cause issues for existing configuration that relies and handles the field as carrying that trailing `\n`: removing it will most certainly cause issues for those codebases, and it wouldn't gain us much (getting rid of it is a `trim()` call away in pretty much any language).

I hope this clarifies why we will not be changing this.
